name: eatsipy_customer
description: Eatsipy food ordering app for customer

version: 1.2.10+20

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  firebase_database: ^12.4.2
  firebase_storage: ^13.4.2
  firebase_messaging: ^16.3.0
  firebase_app_check: ^0.4.4+2

  qr_code_dart_scan: ^0.11.5
  crypto: ^3.0.7
  country_code_picker: ^3.4.1
  dotted_border: ^3.1.0
  geocoding: ^4.0.0
  googleapis_auth: ^2.3.1

  cached_network_image: ^3.4.1
  flutter_easyloading: ^3.0.5
  flutter_email_sender: ^9.0.0
  flutter_html: ^3.0.0
  flutter_local_notifications: ^21.0.0
  flutter_svg: ^2.3.0
  geolocator: ^14.0.2
  location: ^8.0.1
  get: ^4.7.3
  google_sign_in: ^7.2.0
  image_picker: ^1.2.2
  intl: ^0.20.2
  pin_code_fields: ^9.4.0

  provider: ^6.1.5+1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.5
  sign_in_with_apple: ^8.1.0
  syncfusion_flutter_datepicker: ^33.2.10
  timer_count_down: ^2.2.2
  url_launcher: ^6.3.2
  uuid: ^4.5.3
  date_picker_timeline: ^1.2.7
  flutter_rating_bar: ^4.0.1
  flutter_polyline_points: ^3.1.0
  clipboard: ^3.0.14
  map_launcher: ^4.5.0
  path_provider: ^2.1.5
  video_compress: ^3.1.4
  mailer: ^7.1.0
  bottom_picker: ^4.1.1
  in_app_review: ^2.0.12
  share_plus: ^13.1.0
  photo_view: ^0.15.0
  sqflite: ^2.4.2+1
  badges: ^3.2.0

  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  
  timelines_plus: ^2.0.0
  path: ^1.9.1
  video_player: ^2.11.1

  flutter_stripe: ^12.6.0
  razorpay_flutter: ^1.4.5
  flutter_paypal: ^0.2.1

  google_maps_place_picker_mb_v2: ^1.0.1
  speech_to_text: ^7.4.0
  google_maps_flutter: ^2.17.1
  http: ^1.6.0
  flutter_google_places_hoc081098: ^2.0.0
  foloosi_plugins: ^1.1.0
  phonepe_payment_sdk: ^3.0.2
  

dependency_overrides:
  webview_flutter: ^4.9.0
  package_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_home.svg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  fonts:
    - family: Urbanist-Black
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
    - family: Urbanist-Bold
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
    - family: Urbanist-ExtraBold
      fonts:
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
    - family: Urbanist-ExtraLight
      fonts:
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
    - family: Urbanist-Light
      fonts:
        - asset: assets/fonts/Urbanist-Light.ttf
    - family: Urbanist-Medium
      fonts:
        - asset: assets/fonts/Urbanist-Medium.ttf
    - family: Urbanist-Regular
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
    - family: Urbanist-SemiBold
      fonts:
        - asset: assets/fonts/Urbanist-SemiBold.ttf
    - family: Urbanist-Thin
      fonts:
        - asset: assets/fonts/Urbanist-Thin.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/
