// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZWYbh9ZDsl8UbRZbH_Y0apj3gudV0CXA',
    appId: '1:767332616034:web:3079e8897d470b988c8e3b',
    messagingSenderId: '767332616034',
    projectId: 'eatsipy',
    authDomain: 'eatsipy.firebaseapp.com',
    databaseURL: 'https://eatsipy-default-rtdb.firebaseio.com',
    storageBucket: 'eatsipy.appspot.com',
    measurementId: 'G-SFSNJ5SJQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfNHnUa6Lqk47j4WV1gX8jWbuyrGGxFsc',
    appId: '1:767332616034:android:984b831be8919c288c8e3b',
    messagingSenderId: '767332616034',
    projectId: 'eatsipy',
    databaseURL: 'https://eatsipy-default-rtdb.firebaseio.com',
    storageBucket: 'eatsipy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4WCp-i3XonfSpEjjL305fS4tvatKu2p4',
    appId: '1:767332616034:ios:caaa871ce3f6f66d8c8e3b',
    messagingSenderId: '767332616034',
    projectId: 'eatsipy',
    databaseURL: 'https://eatsipy-default-rtdb.firebaseio.com',
    storageBucket: 'eatsipy.appspot.com',
    androidClientId: '767332616034-0n6hd4k4t6vjhi2o9ov5g2k62m5eb5sk.apps.googleusercontent.com',
    iosClientId: '767332616034-9vd8kbek0k9q3ev06iediasd79e36ohk.apps.googleusercontent.com',
    iosBundleId: 'com.eatsipy.customer.ios',
  );
}
